### ISSUE TITLE
As a developer, I want to use an in-memory SQLite Database for testing, such that our actual database is not influenced by any tests, and such that our tests does not depend on other methods or code other than what is being tested

### ISSUE THREAD

**Issue by Noerklit** [ITU-BDSA23-GROUP15/Chirp#62]
**Acceptance Criteria**

- The database used for testing is stored in memory, pass the string ":memory" instead of a real disk file (see https://sqlite.org/inmemorydb.html)

**Comment by JacobPaerre** [comment]
The in-memory stuff for testing works but no tests has been made yet.

**Comment by JacobPaerre** [comment]
The in-memory stuff has been changed to only use Testcontainers thus using MsSql and no more in-memory.
